# Generated by Django 4.2.26 on 2025-12-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0067_datauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitseries',
            name='type',
            field=models.CharField(blank=True, choices=[('RESIDENT', 'Resident permit'), ('BUSINESS', 'Business permit'), ('CAR_SHARE', 'Car sharing permit'), ('HOME_CARE', 'Home care permit'), ('MOVIE', 'Movie permit'), ('SPECIAL_MONITORING', 'Special monitoring permit'), ('STAFF', 'Staff parking permit')], max_length=32, null=True),
        ),
    ]
