# Generated by Django 4.2.26 on 2025-12-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0068_permitseries_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitsubjectitem',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='permitsubjectitem',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
