# Generated by Django 4.2.26 on 2025-12-15 13:29

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import parkings.fields
import parkings.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parkings', '0069_permitsubjectitem_address_permitsubjectitem_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='subjects',
            field=parkings.fields.CleaningJsonField(blank=True, validators=[parkings.validators.DictListValidator({'address': parkings.validators.NullableTextField(allow_null=True, max_length=50), 'end_time': parkings.validators.TimestampField(), 'registration_number': parkings.validators.TextField(max_length=20), 'start_time': parkings.validators.TimestampField(), 'zip': parkings.validators.NullableTextField(allow_null=True, max_length=10)})]),
        ),
        migrations.CreateModel(
            name='PermitCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='time created')),
                ('time', models.DateTimeField(verbose_name='time')),
                ('time_overridden', models.BooleanField(verbose_name='time was overridden')),
                ('registration_number', models.CharField(max_length=20, verbose_name='registration number')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='location')),
                ('result', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='result')),
                ('allowed', models.BooleanField(verbose_name='permit was allowed')),
                ('found_permit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkings.permit', verbose_name='found permit')),
                ('performer', models.ForeignKey(editable=False, help_text='User who performed the check', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='performer')),
            ],
            options={
                'verbose_name': 'parking permit check',
                'verbose_name_plural': 'parking permit checks',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
